### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jasanpreetn9** [norbeyandresg/hades#31]
Traceback (most recent call last):
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades_ui.py", line 110, in <module>
    HadesUI(parser.parse_args().pl_uri)
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades_ui.py", line 23, in __init__
    self.main_menu()
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades_ui.py", line 53, in main_menu
    action()
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades_ui.py", line 103, in manage_playlists
    self.hades.download_tracks(pl)
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades.py", line 156, in download_tracks
    pl_details = self.get_playlist_details(pl_uri)
  File "/Users/jasanpreetnagra/Desktop/Projects/Programming/Python/hades-main/hades.py", line 99, in get_playlist_details
    "album_art": item["track"]["album"]["images"][0]["url"],
IndexError: list index out of range

**Comment by ghost** [comment]
Have you tried adding a check to make sure the **images** list isn't empty before accessing its elements?
